const express = require("express");
require("dotenv").config();
var { graphqlHTTP } = require("express-graphql");
const { makeExecutableSchema } = require("graphql-tools");
const { typeDefs, resolvers } = require("./gql");
const models = require("./models");
const app = express();
const path = "/graphql";
const schema = makeExecutableSchema({ typeDefs, resolvers });
const port = process.env.NODE_PORT;
app.use(path, graphqlHTTP({ schema, graphiql: true, context: { models } }));
app.listen(port);
console.log(`Running a GraphQL API server at http://localhost:${port + path}`);
